### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by antonve** [antonve/ory-experiment#1]
## Todo

* [x] Get Kong to work
* [x] Install Kratos with api endpoints exposed
* [x] Minimal test UI to register and sign in in NextJS
* [x] Check status code for 400 before updating flow when catching errors
* [ ] Are hooks for protecting pages the best way? idk
* [x] Proper post-register handling
* [ ] Error boundaries in case Kratos is unavailable
* [x] Remove automatic log in after creating account to lead the user towards verifying an account
* Make sure all error states are properly handled
